name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2
        with:
          build_only: true
          jekyll_build_options: -d _site

  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: chabad360/htmlproofer@master
        with:
          directory: "_site"
          # The directory to scan
          arguments: --url-swap "https\:\/\/www\.earthdatascience\.org\/images:/images" --file-ignore /example-leaflet-maps/ --http-status-ignore "301"
          # The arguments to pass to HTMLProofer
